# Config borrowed from geojupyter.org GitHub - https://github.com/geojupyter/geojupyter.org
version: 2

build:
  os: "ubuntu-lts-latest"

  commands:
    - "asdf plugin add pixi"
    - "asdf install pixi latest"
    - "asdf global pixi latest"

    - "asdf plugin add r https://github.com/asdf-community/asdf-r.git"

    - "pixi add nbformat pyyaml nbclient"

    - "pixi run render"
    - "mkdir --parents $READTHEDOCS_OUTPUT/html/"
    - "mv _site/* $READTHEDOCS_OUTPUT/html/."
