---
title: "Geodynamics"
subtitle: "Lesson 1.2 - Earth impressions"
author: "David Whipp, University of Helsinki"
institute: "firstname.lastname@helsinki.fi"
format:
  revealjs: 
    slide-number: true
    chalkboard: 
      buttons: false
    preview-links: auto
    logo: /img/HY_logo.png
    css: /css/styles.css
    theme: serif
    footer: '[https://geodynamics-course.github.io](https://geodynamics-course.github.io)'
bibliography: ../references.bib
---

## Goals for this lesson

- Review various observables from Earth's surface and interior

## Topography {.smaller}

:::: {.columns}

::: {.column width="40%"}
![Topography of Earth, Venus, and Mars. Fig. 1.1 of Becker and Faccenna [-@Becker2025].](img/bf-f1.1.png){height="500"}
:::

::: {.column width="60%"}
- Topography provides insight into processes shaping planets' surfaces and interior dynamics
- In these planetary perspectives, the color scheme highlights landscape differences between nearby planets
- Plate tectonics plays a significant role shaping Earth's topography
:::

::::

## The role of isostasy {.smaller}

:::: {.columns}

::: {.column width="40%"}
![Isostatic balance for a lithospheric and asthenospheric column. Fig. 1.3 of Becker and Faccenna [-@Becker2025].](img/bf-f1.3.png){height="500"}
:::

::: {.column width="60%"}
- Much of the elevation difference between continental and oceanic regions on Earth can be related to **isostasy**
- At isostatic equilibrium, neighboring columns of rock will have equal pressure from the weight of the overlying rock at equal depth
- Mathematically, we can say

    \begin{equation}
    p_{l} = \rho g h = \int dz \rho(z) g(z)
    \end{equation}

    where $p_{l}$ is the lithostatic pressure, $\rho$ is rock density, $g$ is the acceleration due to gravity, $h$ is the thickness of rock, and $z$ is depth.
:::

::::

## Calculating isostatic equilibrium {.smaller}

![Crustal block floating on the mantle. Fig. 2.2 of Turcotte and Schubert [-@Turcotte2014].](img/ts-f2.2.jpg)

Let's consider a crustal block "floating" on the mantle.

- The crust “floats” because a typical crustal density $\rho_{\mathrm{c}}$ is ~2750 kg m<sup>-3</sup> whereas the mantle density $\rho_{\mathrm{m}}$ is ~3300 kg m<sup>-3</sup> (i.e., its buoyant)

In hydrostatic equilibrium the weight of a crustal column of thickness $h$ is equal to that of the mantle beside it at the depth of its base $b$, or

\begin{equation}
\rho_{\mathrm{c}} h = \rho_{\mathrm{m}} b
\end{equation}

## References