---
title: "Geodynamics"
subtitle: "Lesson 1.1 - What is Geodynamics?"
author: "David Whipp, University of Helsinki"
institute: "firstname.lastname@helsinki.fi"
format:
  revealjs: 
    slide-number: true
    chalkboard: 
      buttons: false
    preview-links: auto
    logo: /img/HY_logo.png
    css: /css/styles.css
    theme: serif
    footer: '[https://geodynamics-course.github.io](https://geodynamics-course.github.io)'
bibliography: ../references.bib
---

## Practical matters

- Who is the teacher?
- When/where is class?
- What does the course cover?
- What do you need to do?
- Textbook(s), what to bring to class, etc.

All of this can be found in on the course website!<br/>
<https://geodynamics-course.readthedocs.io>.

## Goals for this course

- Provide a general introduction to geodynamics with a <b>focus on the lithosphere</b>
- Review <b>key geodynamic processes and the basic mathematical relationships</b> used to quantify and interpret them
- Establish some sense of the <b>current areas of focus</b> in geodynamic scientific literature
- <b>Enhance your scientific abilities</b> through practical course exercises

## What is geodynamics? {background-image="img/machapuchare.jpg"}

## What is geodynamics? {background-image="img/machapuchare.jpg" background-opacity="0.25"}

::: {.incremental}
- Study of the dynamics of the Earth

    - Physical processes
    - Plate tectonics and other dynamic geological phenomena
:::

## Plate tectonics

![1 billion years of reconstructed tectonic plate motions from Müller et al. [-@Muller2022].](img/muller-animation.mp4){height="500"}

## Isostasy and gravity

![Calculated flexure of intact and broken lithospheric plates. Fig. 3.11 of Becker and Faccenna [-@Becker2025].](img/bf-f3.11.png){height="450"}

## Faulting

![Conceptual brittle damage zone around a strike-slip fault zone. Fig. 3.22 of Becker and Faccenna [-@Becker2025].](img/bf-f3.22.png){height="450"}

## Stress, strain, and rheology

![Oceanic lithospheric strength profiles for various ages. Fig. 5.12 of Becker and Faccenna [-@Becker2025].](img/bf-f5.12.png){height="450"}

## Heat transfer






